name: Test

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      python_version: 3.11

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install jsonschema
      - name: Generate Test CCDLs
        run: python ccdl-generator/ccdl_generator.py -i test/resources/test-data.json -o target/resources/generated-ccdls/
      - name: Run tests
        run: pytest
